-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 14:13:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sensordb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sensordb` ;

-- -----------------------------------------------------
-- Schema sensordb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sensordb` DEFAULT CHARACTER SET utf8 ;
USE `sensordb` ;

-- -----------------------------------------------------
-- Table `sensordb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sensordb`.`Account` ;

CREATE TABLE IF NOT EXISTS `sensordb`.`Account` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `secret` VARCHAR(128) NULL,
  `key` VARCHAR(128) NULL,
  `mailaddr` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(255) NULL,
  `ulevel` INT NULL DEFAULT 10,
  `effectivedate` DATETIME NULL,
  `expiredate` DATETIME NULL,
  `lastupdate` TIMESTAMP NULL,
  `idstatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensordb`.`Node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sensordb`.`Node` ;

CREATE TABLE IF NOT EXISTS `sensordb`.`Node` (
  `nid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT UNSIGNED NOT NULL,
  `nodename` VARCHAR(255) NOT NULL,
  `macaddr` VARCHAR(32) NOT NULL,
  `effectivedate` DATETIME NULL,
  `expiredate` DATETIME NULL,
  `lastupdate` TIMESTAMP NULL,
  `idstatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensordb`.`NodeValue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sensordb`.`NodeValue` ;

CREATE TABLE IF NOT EXISTS `sensordb`.`NodeValue` (
  `nvid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nid` INT UNSIGNED NOT NULL,
  `geo` VARCHAR(128) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `altitude` DOUBLE NULL,
  `temperature` DOUBLE(8,2) NULL,
  `humidity` DOUBLE(8,2) NULL,
  `pressure` DOUBLE(8,2) NULL,
  `co2` DOUBLE(8,2) NULL,
  `wbgt` DOUBLE(6,2) NULL,
  `effectivedate` DATETIME NULL,
  `idstatus` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`nvid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensordb`.`ValueRaw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sensordb`.`ValueRaw` ;

CREATE TABLE IF NOT EXISTS `sensordb`.`ValueRaw` (
  `vid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nid` INT UNSIGNED NOT NULL,
  `effectivedate` DATETIME NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`vid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
